### ISSUE TITLE
Docker Compose Up - Java Service

### ISSUE THREAD

**Issue by ammarbrohi** [ChrisJBurns/jaeger-distributed-tracing-demo#2]
`docker compose up` starts with building java service and fails at  ${JAR_FILE}

Building jaeger-tracing-java-service
Step 1/5 : FROM openjdk:11.0.7-jre-slim
 ---> 030d68516e3a
Step 2/5 : ARG JAR_FILE=build/libs/jaeger-tracing-java-service-0.0.1-SNAPSHOT.jar
 ---> Using cache
 ---> 9499e1d68d81
Step 3/5 : COPY opentelemetry-javaagent-all.jar opentelemetry-javaagent-all.jar
 ---> Using cache
 ---> 94782e1645fc
Step 4/5 : COPY ${JAR_FILE} app.jar
ERROR: Service 'jaeger-tracing-java-service' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder993931537/build/libs/jaeger-tracing-java-service-0.0.1-SNAPSHOT.jar: no such file or directory

**Comment by ChrisJBurns** [comment]
You'll need to build the Java project before you do a docker-compose up, this is so it can select the correct .jar to put inside the image. Apologies if this was missed.

**Comment by ChrisJBurns** [comment]
Closing as no further comments from original poster.
